openapi: 3.1.1
info:
  title: payment api
  description: "la v1 d'un service de paiement"
  version: "1.0.0"

servers:
  - url: https://localhost:8080

paths:
  /v1/payments/{uuid}:
    get:
      summary: get status of a transactions by uuid
      operationId: getPayment
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: strings
            format: uuid
      responses:
        "200":
          description: the status of request transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [SUCCEEDED, FAILED, REQUIRES_ACTION]
                    description: the status of transactioon
    post:
      summary: Create a new transaction
      operationId: createPayment
      parameters:
        - in: header
          name: X-Tenant-Id
          description: for idempotency
          schema:
            type: string
            pattern: ^t-[0-9]+$
            example: t-45
        - in: header
          name: Idempotency-Key
          description: for idempotency
          schema:
            type: string
            pattern: ^k-[0-9]+$
            example: k-45
      requestBody:
        description: insert order , amount and currency for a transaction
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
                  example: 14.59
                  description: amount of transaction
                orderRef:
                  type: string
                  pattern: ^ORD-[0-9]+$
                  example: ORD-123
                  description: order of transaction
                currency:
                  type: string
                  description: currency of transaction
      responses:
        "202":
          description: uuid and status of the new transaction
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    format: uuid
                    description: uuid of the new transaction
                  status:
                    type: string
                    enum: [SUCCEEDED, FAILED, REQUIRES_ACTION]
                    description: status of the new transaction
